export interface LanguageInfo {
  id: string
  name: string
  aliases?: string[]
}

// Generated from shiki's bundledLanguagesInfo (~235 grammars) -- a data
// change only, not new tokenizing logic; lib/shiki/tokenize.ts already
// accepts any of shiki's bundled language ids unchanged. Aliases (e.g.
// 'lean4' for 'lean', 'py' for 'python') are resolved by Shiki itself, so
// any code block already storing an old alias as its `language` value
// keeps tokenizing correctly even though the picker below shows the
// canonical id.
export const LANGUAGES: LanguageInfo[] = [
  { id: 'bsl', name: '1C (Enterprise)', aliases: ['1c'] },
  { id: 'sdbl', name: '1C (Query)', aliases: ['1c-query'] },
  { id: 'abap', name: 'ABAP' },
  { id: 'actionscript-3', name: 'ActionScript' },
  { id: 'ada', name: 'Ada' },
  { id: 'angular-html', name: 'Angular HTML' },
  { id: 'angular-ts', name: 'Angular TypeScript' },
  { id: 'apache', name: 'Apache Conf' },
  { id: 'apex', name: 'Apex' },
  { id: 'apl', name: 'APL' },
  { id: 'applescript', name: 'AppleScript' },
  { id: 'ara', name: 'Ara' },
  { id: 'asciidoc', name: 'AsciiDoc', aliases: ['adoc'] },
  { id: 'razor', name: 'ASP.NET Razor' },
  { id: 'asm', name: 'Assembly' },
  { id: 'astro', name: 'Astro' },
  { id: 'awk', name: 'AWK' },
  { id: 'ballerina', name: 'Ballerina' },
  { id: 'bat', name: 'Batch File', aliases: ['batch'] },
  { id: 'beancount', name: 'Beancount' },
  { id: 'berry', name: 'Berry', aliases: ['be'] },
  { id: 'bibtex', name: 'BibTeX' },
  { id: 'bicep', name: 'Bicep' },
  { id: 'bird2', name: 'BIRD2 Configuration', aliases: ['bird'] },
  { id: 'blade', name: 'Blade' },
  { id: 'c', name: 'C' },
  { id: 'csharp', name: 'C#', aliases: ['c#','cs'] },
  { id: 'cpp', name: 'C++', aliases: ['c++'] },
  { id: 'c3', name: 'C3' },
  { id: 'cadence', name: 'Cadence', aliases: ['cdc'] },
  { id: 'cairo', name: 'Cairo' },
  { id: 'clarity', name: 'Clarity' },
  { id: 'clojure', name: 'Clojure', aliases: ['clj'] },
  { id: 'soy', name: 'Closure Templates', aliases: ['closure-templates'] },
  { id: 'cmake', name: 'CMake' },
  { id: 'cobol', name: 'COBOL' },
  { id: 'codeowners', name: 'CODEOWNERS' },
  { id: 'codeql', name: 'CodeQL', aliases: ['ql'] },
  { id: 'coffee', name: 'CoffeeScript', aliases: ['coffeescript'] },
  { id: 'common-lisp', name: 'Common Lisp', aliases: ['lisp'] },
  { id: 'coq', name: 'Coq' },
  { id: 'crystal', name: 'Crystal' },
  { id: 'css', name: 'CSS' },
  { id: 'csv', name: 'CSV' },
  { id: 'cue', name: 'CUE' },
  { id: 'cypher', name: 'Cypher', aliases: ['cql'] },
  { id: 'd', name: 'D' },
  { id: 'dart', name: 'Dart' },
  { id: 'dax', name: 'DAX' },
  { id: 'desktop', name: 'Desktop' },
  { id: 'diff', name: 'Diff' },
  { id: 'docker', name: 'Dockerfile', aliases: ['dockerfile'] },
  { id: 'dotenv', name: 'dotEnv' },
  { id: 'dream-maker', name: 'Dream Maker' },
  { id: 'edge', name: 'Edge' },
  { id: 'elixir', name: 'Elixir' },
  { id: 'elm', name: 'Elm' },
  { id: 'emacs-lisp', name: 'Emacs Lisp', aliases: ['elisp'] },
  { id: 'erb', name: 'ERB' },
  { id: 'erlang', name: 'Erlang', aliases: ['erl'] },
  { id: 'fsharp', name: 'F#', aliases: ['f#','fs'] },
  { id: 'fennel', name: 'Fennel' },
  { id: 'fish', name: 'Fish' },
  { id: 'fluent', name: 'Fluent', aliases: ['ftl'] },
  { id: 'fortran-fixed-form', name: 'Fortran (Fixed Form)', aliases: ['f','for','f77'] },
  { id: 'fortran-free-form', name: 'Fortran (Free Form)', aliases: ['f90','f95','f03','f08','f18'] },
  { id: 'gdresource', name: 'GDResource', aliases: ['tscn','tres'] },
  { id: 'gdscript', name: 'GDScript', aliases: ['gd'] },
  { id: 'gdshader', name: 'GDShader' },
  { id: 'genie', name: 'Genie' },
  { id: 'po', name: 'Gettext PO', aliases: ['pot','potx'] },
  { id: 'gherkin', name: 'Gherkin' },
  { id: 'git-commit', name: 'Git Commit Message' },
  { id: 'git-rebase', name: 'Git Rebase Message' },
  { id: 'gleam', name: 'Gleam' },
  { id: 'glimmer-js', name: 'Glimmer JS', aliases: ['gjs'] },
  { id: 'glimmer-ts', name: 'Glimmer TS', aliases: ['gts'] },
  { id: 'glsl', name: 'GLSL' },
  { id: 'gn', name: 'GN' },
  { id: 'gnuplot', name: 'Gnuplot' },
  { id: 'go', name: 'Go' },
  { id: 'graphql', name: 'GraphQL', aliases: ['gql'] },
  { id: 'groovy', name: 'Groovy' },
  { id: 'hack', name: 'Hack' },
  { id: 'handlebars', name: 'Handlebars', aliases: ['hbs'] },
  { id: 'hcl', name: 'HashiCorp HCL' },
  { id: 'haskell', name: 'Haskell', aliases: ['hs'] },
  { id: 'haxe', name: 'Haxe' },
  { id: 'hjson', name: 'Hjson' },
  { id: 'hlsl', name: 'HLSL' },
  { id: 'html', name: 'HTML' },
  { id: 'html-derivative', name: 'HTML (Derivative)' },
  { id: 'http', name: 'HTTP' },
  { id: 'hurl', name: 'Hurl' },
  { id: 'hxml', name: 'HXML' },
  { id: 'hy', name: 'Hy' },
  { id: 'imba', name: 'Imba' },
  { id: 'ini', name: 'INI', aliases: ['properties'] },
  { id: 'java', name: 'Java' },
  { id: 'javascript', name: 'JavaScript', aliases: ['js','cjs','mjs'] },
  { id: 'jinja', name: 'Jinja' },
  { id: 'jison', name: 'Jison' },
  { id: 'json', name: 'JSON' },
  { id: 'jsonl', name: 'JSON Lines' },
  { id: 'jsonc', name: 'JSON with Comments' },
  { id: 'json5', name: 'JSON5' },
  { id: 'jsonnet', name: 'Jsonnet' },
  { id: 'jssm', name: 'JSSM', aliases: ['fsl'] },
  { id: 'jsx', name: 'JSX' },
  { id: 'julia', name: 'Julia', aliases: ['jl'] },
  { id: 'just', name: 'Just' },
  { id: 'kdl', name: 'KDL' },
  { id: 'kotlin', name: 'Kotlin', aliases: ['kt','kts'] },
  { id: 'kusto', name: 'Kusto', aliases: ['kql'] },
  { id: 'latex', name: 'LaTeX' },
  { id: 'lean', name: 'Lean 4', aliases: ['lean4'] },
  { id: 'less', name: 'Less' },
  { id: 'liquid', name: 'Liquid' },
  { id: 'llvm', name: 'LLVM IR' },
  { id: 'log', name: 'Log file' },
  { id: 'logo', name: 'Logo' },
  { id: 'lua', name: 'Lua' },
  { id: 'luau', name: 'Luau' },
  { id: 'make', name: 'Makefile', aliases: ['makefile'] },
  { id: 'markdown', name: 'Markdown', aliases: ['md'] },
  { id: 'marko', name: 'Marko' },
  { id: 'matlab', name: 'MATLAB' },
  { id: 'mdc', name: 'MDC' },
  { id: 'mdx', name: 'MDX' },
  { id: 'mermaid', name: 'Mermaid', aliases: ['mmd'] },
  { id: 'mipsasm', name: 'MIPS Assembly', aliases: ['mips'] },
  { id: 'mojo', name: 'Mojo' },
  { id: 'moonbit', name: 'MoonBit', aliases: ['mbt','mbti'] },
  { id: 'move', name: 'Move' },
  { id: 'narrat', name: 'Narrat Language', aliases: ['nar'] },
  { id: 'nextflow', name: 'Nextflow', aliases: ['nf'] },
  { id: 'nextflow-groovy', name: 'Nextflow Groovy' },
  { id: 'nginx', name: 'Nginx' },
  { id: 'nim', name: 'Nim' },
  { id: 'nix', name: 'Nix' },
  { id: 'nushell', name: 'nushell', aliases: ['nu'] },
  { id: 'objective-c', name: 'Objective-C', aliases: ['objc'] },
  { id: 'objective-cpp', name: 'Objective-C++' },
  { id: 'ocaml', name: 'OCaml' },
  { id: 'odin', name: 'Odin' },
  { id: 'openscad', name: 'OpenSCAD', aliases: ['scad'] },
  { id: 'pascal', name: 'Pascal' },
  { id: 'perl', name: 'Perl' },
  { id: 'php', name: 'PHP' },
  { id: 'pkl', name: 'Pkl' },
  { id: 'plsql', name: 'PL/SQL' },
  { id: 'polar', name: 'Polar' },
  { id: 'postcss', name: 'PostCSS' },
  { id: 'powerquery', name: 'PowerQuery' },
  { id: 'powershell', name: 'PowerShell', aliases: ['ps','ps1'] },
  { id: 'prisma', name: 'Prisma' },
  { id: 'prolog', name: 'Prolog' },
  { id: 'proto', name: 'Protocol Buffer 3', aliases: ['protobuf'] },
  { id: 'pug', name: 'Pug', aliases: ['jade'] },
  { id: 'puppet', name: 'Puppet' },
  { id: 'purescript', name: 'PureScript' },
  { id: 'python', name: 'Python', aliases: ['py'] },
  { id: 'qml', name: 'QML' },
  { id: 'qmldir', name: 'QML Directory' },
  { id: 'qss', name: 'Qt Style Sheets' },
  { id: 'r', name: 'R' },
  { id: 'racket', name: 'Racket' },
  { id: 'raku', name: 'Raku', aliases: ['perl6'] },
  { id: 'regexp', name: 'RegExp', aliases: ['regex'] },
  { id: 'rel', name: 'Rel' },
  { id: 'rst', name: 'reStructuredText' },
  { id: 'riscv', name: 'RISC-V' },
  { id: 'ron', name: 'RON' },
  { id: 'rosmsg', name: 'ROS Interface' },
  { id: 'ruby', name: 'Ruby', aliases: ['rb'] },
  { id: 'haml', name: 'Ruby Haml' },
  { id: 'rust', name: 'Rust', aliases: ['rs'] },
  { id: 'sas', name: 'SAS' },
  { id: 'sass', name: 'Sass' },
  { id: 'scala', name: 'Scala' },
  { id: 'scheme', name: 'Scheme' },
  { id: 'scss', name: 'SCSS' },
  { id: 'shaderlab', name: 'ShaderLab', aliases: ['shader'] },
  { id: 'shellscript', name: 'Shell', aliases: ['bash','sh','shell','zsh'] },
  { id: 'shellsession', name: 'Shell Session', aliases: ['console'] },
  { id: 'smalltalk', name: 'Smalltalk' },
  { id: 'solidity', name: 'Solidity' },
  { id: 'sparql', name: 'SPARQL' },
  { id: 'splunk', name: 'Splunk Query Language', aliases: ['spl'] },
  { id: 'sql', name: 'SQL' },
  { id: 'ssh-config', name: 'SSH Config' },
  { id: 'stata', name: 'Stata' },
  { id: 'stylus', name: 'Stylus', aliases: ['styl'] },
  { id: 'surrealql', name: 'SurrealQL', aliases: ['surql'] },
  { id: 'svelte', name: 'Svelte' },
  { id: 'swift', name: 'Swift' },
  { id: 'systemd', name: 'Systemd Units' },
  { id: 'system-verilog', name: 'SystemVerilog' },
  { id: 'talonscript', name: 'TalonScript', aliases: ['talon'] },
  { id: 'tasl', name: 'Tasl' },
  { id: 'tcl', name: 'Tcl' },
  { id: 'templ', name: 'Templ' },
  { id: 'terraform', name: 'Terraform', aliases: ['tf','tfvars'] },
  { id: 'tex', name: 'TeX' },
  { id: 'toml', name: 'TOML' },
  { id: 'tsv', name: 'TSV' },
  { id: 'tsx', name: 'TSX' },
  { id: 'turtle', name: 'Turtle' },
  { id: 'twig', name: 'Twig' },
  { id: 'typescript', name: 'TypeScript', aliases: ['ts','cts','mts'] },
  { id: 'ts-tags', name: 'TypeScript with Tags', aliases: ['lit'] },
  { id: 'typespec', name: 'TypeSpec', aliases: ['tsp'] },
  { id: 'typst', name: 'Typst', aliases: ['typ'] },
  { id: 'v', name: 'V' },
  { id: 'vala', name: 'Vala' },
  { id: 'verilog', name: 'Verilog' },
  { id: 'vhdl', name: 'VHDL' },
  { id: 'viml', name: 'Vim Script', aliases: ['vim','vimscript'] },
  { id: 'vb', name: 'Visual Basic', aliases: ['cmd'] },
  { id: 'vue', name: 'Vue' },
  { id: 'vue-html', name: 'Vue HTML' },
  { id: 'vue-vine', name: 'Vue Vine' },
  { id: 'vyper', name: 'Vyper', aliases: ['vy'] },
  { id: 'wasm', name: 'WebAssembly' },
  { id: 'wit', name: 'WebAssembly Interface Types' },
  { id: 'wenyan', name: 'Wenyan', aliases: ['文言'] },
  { id: 'wgsl', name: 'WGSL' },
  { id: 'wikitext', name: 'Wikitext', aliases: ['mediawiki','wiki'] },
  { id: 'reg', name: 'Windows Registry Script' },
  { id: 'wolfram', name: 'Wolfram', aliases: ['wl'] },
  { id: 'xml', name: 'XML' },
  { id: 'xsl', name: 'XSL' },
  { id: 'yaml', name: 'YAML', aliases: ['yml'] },
  { id: 'zenscript', name: 'ZenScript' },
  { id: 'zig', name: 'Zig' },
]

export const THEMES = [
  'dracula',
  'nord',
  'one-dark-pro',
  'github-dark',
  'github-light',
  'monokai',
  'catppuccin-mocha',
  'vitesse-dark',
  'vitesse-light',
  'material-theme-ocean',
] as const

export const DEFAULT_LANGUAGE = 'python'
export const DEFAULT_THEME: (typeof THEMES)[number] = 'dracula'

// Static preview colors for the Inspector's theme swatch picker -- bg/fg
// match each theme's actual resolved editor.background/foreground (checked
// against the bundled @shikijs/themes source); the two accent dots are
// representative, not exact token colors, purely for a recognizable preview.
export const THEME_PREVIEWS: Record<
  (typeof THEMES)[number],
  { bg: string; fg: string; accents: [string, string] }
> = {
  dracula: { bg: '#282a36', fg: '#f8f8f2', accents: ['#ff79c6', '#50fa7b'] },
  nord: { bg: '#2e3440', fg: '#d8dee9', accents: ['#88c0d0', '#a3be8c'] },
  'one-dark-pro': { bg: '#282c34', fg: '#abb2bf', accents: ['#e06c75', '#61afef'] },
  'github-dark': { bg: '#24292e', fg: '#e1e4e8', accents: ['#79c0ff', '#ffa657'] },
  'github-light': { bg: '#ffffff', fg: '#24292e', accents: ['#0550ae', '#8250df'] },
  monokai: { bg: '#272822', fg: '#f8f8f2', accents: ['#f92672', '#a6e22e'] },
  'catppuccin-mocha': { bg: '#1e1e2e', fg: '#cdd6f4', accents: ['#cba6f7', '#a6e3a1'] },
  'vitesse-dark': { bg: '#121212', fg: '#dbd7caee', accents: ['#e6cc77', '#4d9375'] },
  'vitesse-light': { bg: '#ffffff', fg: '#393a34', accents: ['#b07d48', '#388a34'] },
  'material-theme-ocean': { bg: '#0f111a', fg: '#babed8', accents: ['#89ddff', '#f78c6c'] },
}

export const FONT_OPTIONS = [
  { key: 'geist-mono', label: 'Geist Mono', cssVar: '--font-geist-mono' },
  { key: 'jetbrains-mono', label: 'JetBrains Mono', cssVar: '--font-jetbrains-mono' },
  { key: 'fira-code', label: 'Fira Code', cssVar: '--font-fira-code' },
  { key: 'ibm-plex-mono', label: 'IBM Plex Mono', cssVar: '--font-ibm-plex-mono' },
] as const

export const DEFAULT_FONT_KEY: (typeof FONT_OPTIONS)[number]['key'] = 'geist-mono'

export function fontCssVar(key: string | undefined): string {
  return FONT_OPTIONS.find((f) => f.key === key)?.cssVar ?? FONT_OPTIONS[0].cssVar
}
